---

- name: "Copy Zookeeper and Kafka files"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "zookeeper"
    group: "zookeeper"
  with_items:
    - { src: 'zookeeper.properties.j2', dest: '/opt/zookeeper/conf/zookeeper.properties' }
    - { src: 'kafka_server_properties.j2', dest: '/opt/kafka/config/server.properties'}

- name: Create MyId files for zookeeper
  copy:
    content={{ item.0 + 1 }}
    dest=/var/lib/zookeeper/myid
  with_indexed_items: "{{groups['kafka']}}"
  when: item.1 == "{{inventory_hostname}}"

- name: Run the Zookeeper service
  service: name=zookeeper state=started enabled=yes

# - name: Run the Zookeeper service
#   systemd: state=started name=zookeeper

- name: Run the kafka service via init
  service: name=kafka state=started enabled=yes

# - name: Run the kafka service via systemd
#   systemd: state=started name=kafka